### ISSUE TITLE
Empty switch page and no icons on floorplan

### ISSUE THREAD

**Issue by evilmumi** [viny182/KFloorP#3]
Thanks for this nice project.
I started with a httpd docker to host the files.

i can open page on pc and kindle but i think there is a missing communication

yaml:

```
api:

http:
    cors_allowed_origins:
    - 'null'
    - http://192.168.0.146:5580
    - http://192.168.0.146:5580/
```

data.js    
```
var hassaddress = "http://192.168.0.148:8123/"; 
var hasspass = "verylongtoken"; 

var devices1stFloor = [
  ["light.ikea01", 450, 510],
  ["switch.steckdose_homeoffice", 500, 530, "dishwasher"]
];
var devices2ndFloor = [];
```
![Unbenannt](https://github.com/viny182/KFloorP/assets/23313699/bc555994-13db-4dd5-b304-5c34c050e9ee)

i restarted homeassistant but not the whole os

**Comment by viny182** [comment]
Hello @evilmumi,

The IP on your yaml is 192.168.0.146 but in your data.js is 192.168.0.148.... can you confirm the right address?

Also, could you open the browsers console (f12) and past a screenshot in here?

**Comment by evilmumi** [comment]
> Hello @evilmumi,
> 
> The IP on your yaml is 192.168.0.146 but in your data.js is 192.168.0.148.... can you confirm the right address?
> 
> Also, could you open the browsers console (f12) and past a screenshot in here?

146 ist the docker with httpd port 5580
148 is Homeassistant

![image](https://github.com/viny182/KFloorP/assets/23313699/7b0e0ac2-c83a-41d6-adbc-0f3144dc87fe)
I see the a double // in the API URL i try to fix that.
that was the fault.

wrong: var hassaddress = "http://192.168.0.148:8123/"; 
correct: var hassaddress = "http://192.168.0.148:8123";
